### ISSUE TITLE
UI Improvement to showcase if a column is sorted or not

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1244]
**Background**
Currently, when sorting is applied on a column there is no visual indicator to show which column the sorting is applied on. This results in confusion for users.

**Solution **
Add a button similar to the Filter button for indicating whether sorting is applied on a table or not. 
![Screenshot 2023-05-04 at 3 26 54 pm](https://user-images.githubusercontent.com/307298/236118906-4cc447e2-631b-465d-8e58-30a0690a876f.png)

Also when sorting is applied it shows the column by which the sorting is applied and the order.
![Screenshot 2023-05-04 at 3 28 15 pm](https://user-images.githubusercontent.com/307298/236119112-caed044e-1c03-4c25-b054-1428d97ff38d.png)

**Comment by harshbisle** [comment]
I would like to work on this. We should add a sort button as it is shown in the images right?

**Comment by harinij** [comment]
Hi @harshbisle yes - it needs to have th sorting button when sort is applied to a column to indicate that it is active on that table.

**Comment by harshbisle** [comment]
Hi @harinij, Awesome. Thank you for letting me give this a shot.

**Comment by harinij** [comment]
Hi @harshbisle any updates? If not we will be opening this up for anyone to submit PR. Thanks

**Comment by harshbisle** [comment]
Hi @harinij, please accept  my apologies for the delay. I was caught up with some unexpected things. However, I will submit a PR by the end of this week. Is that feasible? if not, please go ahead with your decision.

**Comment by harshbisle** [comment]
Hey, @harinij I sincerely regret the delay in addressing the issue. Unfortunately, due to unforeseen circumstances, I couldn't work on it within the agreed timeframe. I understand the importance of a timely resolution, and I wanted to let you know about my situation.

Given the circumstances, I kindly request that you consider opening this issue for anyone else who is available to work on it. I genuinely regret having to let go of this issue.

Rest assured, I am committed to returning and contributing to the project as soon as I am able to. Thank you for your understanding and for considering my request.

**Comment by mnmt7** [comment]
Hey @harinij, can I work on this issue?

**Comment by harinij** [comment]
Hi @mnmt7 sure thank you, I have assined it to you now.

**Comment by harshbisle** [comment]
@mnmt7 Well done! 👏

**Comment by harinij** [comment]
Thanks @mnmt7 for the contribution :) Btw I have sent you an email, looking to connect!
