### ISSUE TITLE
Add option to delete workspaces via right-click menu.

### ISSUE THREAD

**Issue by munneb10** [rowyio/rowy#1270]
### Overview
- Add a "Delete" option to the right-click menu for workspaces. This would make it easy for users to delete workspaces that they no longer need.

- Add a confirmation prompt when a user tries to delete a workspace. This would prevent users from accidentally deleting workspaces.

- Add a warning message when a user tries to delete a workspace that contains data. This would remind users that deleting the workspace will also delete all of the data in the workspace.

### Little bit more detailed Description

- The "Delete" option should be added to the right-click menu for workspaces. This would make it easy for users to find the option and would be consistent with other right-click menus in rowy.

- The confirmation prompt should be displayed when a user tries to delete a workspace. This would give the user a chance to change their mind before the workspace is deleted.

- The warning message should be displayed when a user tries to delete a workspace that contains data. This would remind the user that deleting the workspace will also delete all of the data in the workspace.

**Comment by munneb10** [comment]
If this issue worth it. I will be very happy to contribute for this issue.
Thanks

**Comment by harinij** [comment]
Hi @munneb10 currently this option is available workspace settings. Since this is not an action we expect to be frequent, putting it in the right click menu would not be ideal from a design stand point. If there is any specific reason why the workspace setting delete option doesn't work for you please share as an issue. Closing this for now as it is out of scope.
