### ISSUE TITLE
Disable "Apply sorting for all users" dialog

### ISSUE THREAD

**Issue by slvkrvnsv** [rowyio/rowy#1386]
**Is your feature request related to a problem? Please describe.**
I'm the only user and while working with the db I do a lot of sorting, filtering, column width changes.
This thing is distracting me all the time :( Because for each click there is always one more click.

**Describe the solution you'd like**
Don't ask "Apply sorting for all users" and all similar messages when there's only one user on the plan.

**Describe alternatives you've considered**
Dunno, Google Sheets doesn't ask me this even if 15 people at the same page ;D

**Comment by harinij** [comment]
@slvkrvnsv that's a good point. Agree that it can be distracting if you are doing a lot of sorting. Will add the ability to disable it.

**Comment by nithinrdy** [comment]
Hey @harinij, mind if I take a stab at this?

- One approach is obviously to add some sort of option to, say, the table settings (could be project-wide too perhaps) to disable the prompt when column-widths/sorting etc. are updated. If we were to incorporate this option (say, as a checkbox) into the table settings modal (maybe we could add a fifth `Customization` section underneath `Access Controls`) or into the project settings page (under the existing `Customization` section), we wouldn't need additional designs.

- Another (maybe kinda smarter but less flexible) option is to determine if the prompts should be disabled based on the number of members added to the project. If there's no other members, the prompts shouldn't show up. This would be less flexible because it's possible that even with multiple members a team would like to see no prompts. Again, we wouldn't need any separate designs.

Of course, the first approach will need a lot more thought if this option is supposed to be a per-user thing (although I'm not sure how useful that would be). Thoughts?

**Comment by nithinrdy** [comment]
Additionally, if we choose to go with the first approach, alongside/under the 'disable-prompts' checkbox we could have a pair of radio buttons. The radio options will be inactive if prompts are enabled, but will be active when prompts are disabled.

The two options can be:
 - Update changes in properties for all users.
 - Do not update properties for all users.

Essentially, the type of default behaviour the user wishes to see when prompts are disabled.

**Comment by harinij** [comment]
Hi @nithinrdy - great I have assigned it to you. I like the first approach you mentioned however instead of it being a table setting, or project wide, it can be per user setting. We have user settings here: src/components/Settings/UserSettings/Theme.tsx
Under the account panel, here we can under preferences, add another section called "Table Settings" - which can have the following checkboxes;  

- "Disable popup - to save sorting changes to the team"
- "Disable popup - to save column width changes to the team"

Plus another two checkbox for:

- "Automatically apply sorting changes to all users" 
- "Automatically apply column width changes to all users" 

<img width="958" alt="Screenshot 2023-09-18 at 12 09 09 pm" src="https://github.com/rowyio/rowy/assets/307298/57906c67-d1c2-4882-854e-8b911a6008c5">

This way we can keep the default behaviour as is, but if someone wants to disable it or auto-apply, then they can do so on their account preferences.

**Comment by nithinrdy** [comment]
Got it, I'll pick this up (thanks for the pointers).

**Comment by bofeiw** [comment]
@nithinrdy is this completed, and is it synced to Rowy app?

**Comment by nithinrdy** [comment]
Yes, here's [the corresponding commit](https://github.com/rowyio/rowyapp/commit/65ba9973f28cc4ae7d23110bafeadb4d19637dd3) on rowyapp.

**Comment by bofeiw** [comment]
Closing this issue as implemented in https://github.com/rowyio/rowy/pull/1419.

In Rowy open source, updated settings section can be found in user settings page.
<img width="984" alt="Screenshot 2024-01-19 at 18 27 46" src="https://github.com/rowyio/rowy/assets/34177142/1e350935-d54d-4770-a3f8-344b65cc2825">

In hosted Rowy app, it can be found in user preferences.
<img width="758" alt="Screenshot 2024-01-19 at 18 28 59" src="https://github.com/rowyio/rowy/assets/34177142/c0ab9b0e-781f-41f0-8e4b-7a9ceee51f38">
