### ISSUE TITLE
Invitation emails not sent

### ISSUE THREAD

**Issue by somenotrandomcoder** [rowyio/rowy#1465]
**Describe the bug**
I tried to invite friend to project but invitation emails are not sent. There is also no link in UI i can just copy paste and send him myself. Tried to invite my other email and also didnt receive invitation email.

**To Reproduce**
1. Go to 'Workspace Settings'
2. Click on 'Members'
3. Click on 'Invite user'
4. Input user email to invite
5. Select role
6. Click "submit"
7. Check mailbox (and spam)

**Expected behavior**
Invitation email with invitation link is sent. (also preferably for such cases as email cron does not work - allow copy pasting invitation link in Members page UI)

**Rowy Run version**
Rowy.io web dashboard

**Additional context**

**Comment by Chadha93** [comment]
Hi @somenotrandomcoder, I just tested this, and it turned out to be working fine. I received the email.

1. Invitation:
![send-invite](https://github.com/rowyio/rowy/assets/65453826/fde6b1d3-4920-4a03-be7d-85874d09df1d)
2. 
![success-invite](https://github.com/rowyio/rowy/assets/65453826/0432def7-2da1-4222-9349-9d1d66287b7e)
3. Email received - 
![image](https://github.com/rowyio/rowy/assets/65453826/f9e58176-f94a-4460-a79d-1cb4eedd66e1)


A few troubleshooting steps to try:
1. Re-check the email.
2. Check the console for any errors, and the networks tab to view the response when clicking on send.

Closing this issue as followed up on this GitHub discussion  - https://github.com/rowyio/rowy/discussions/1464
