### ISSUE TITLE
Filtering items shown on row connection field type based on values from other columns

### ISSUE THREAD

**Issue by kristiankyvik** [rowyio/rowy#204]
Hi! I have created some columns of type row connection. These columns connect to rows of a table that is a group collection (merging items form a series of sub collections). I would like to filter the values the column shows based on the values of other columns. To illustrate, I would like to show the user a filtered list in the search items of buildings based in the company he has selected in the previous column. I see that there is an option for filter template, but there is no documentation on this, so I would really appreciate if you could give me some pointers. Here is an image to explain what I mean:

![image](https://user-images.githubusercontent.com/6661158/93569490-e5d90280-f991-11ea-9ea9-469d266e6d7e.png)

I also wanted to ask, is there anyway of making all items in a row connection selectable at once? Do you plan to support this?

**Comment by shamsmosowi** [comment]
hi @kristiankyvik , filter template can be a static string ```'attribute:value'``` or it can contain a value from any field in the row(Firestore doc) using handlebars( eg:  ```'attribute:{{fieldName}}'```) then passed it into the [algolia filters query parameter](https://www.algolia.com/doc/api-reference/api-parameters/filters/). So if you have a field in your row like ```companyId```, you could to something like this ```company:{{companyId}}```.

for your second question, I'm not sure if we want to do that because we don't know how big the index is, but if you do need that functionality feel free to modify [the component](https://github.com/AntlerVC/firetable/blob/master/www/src/components/ConnectTableSelect/PopupContents.tsx) on your own fork.

**Comment by kristiankyvik** [comment]
Thanks for getting back to me @shamsmosowi. In my case I have a field called companies containing an array of ids ([id1, id2, id3]). I want the the row connection to filter out the items based on the following rule: [id1, id2, id3],contains(item.id). Is this possible using templates in algolia?

**Comment by shamsmosowi** [comment]
unfortunately, I don't think it's possible to do a contains operation using Algolia filters.

the second issue is a bug that doesn't render the stored value of the filter template, it will be fixed soon.

**Comment by harinij** [comment]
Bug fixed in the latest release. Closing the issue for now, please raise again if it is still relevant.

@kristiankyvik Check out our latest easy deployment [link](https://rowy.app/deploy) to migrate to Rowy and do join our discord community if you haven't [already](https://discord.com.gg/B8yAD5PDX4) :)
