### ISSUE TITLE
Add accessible reorder option in column menu

### ISSUE THREAD

**Issue by notsidney** [rowyio/rowy#562]
**Is your feature request related to a problem? Please describe.**
Columns can only be reordered using drag and drop, but this is not an accessible method and moving the column from one end of the table to another is difficult if there are many columns.

**Describe the solution you'd like**
In the column menu, there should be an option to reorder that opens a modal to change the order of columns.

**Comment by gibsonliketheguitar** [comment]
I would like to claim this task.

**Comment by harinij** [comment]
This issue is open, needs design.

Some suggested options, the menu for column can be renamed to "Columns" 
<img width="577" alt="Screen Shot 2022-07-05 at 9 57 23 pm" src="https://user-images.githubusercontent.com/307298/177322591-edb19824-cd77-442c-8613-cd0f2a786c0b.png">

and can allow for drag and drop reorder as shown below (example, not final design suggestion). 

https://user-images.githubusercontent.com/307298/177322742-bca137fc-5bed-4992-9edc-780542797bec.mov

++ @tinacai97

**Comment by notsidney** [comment]
We use [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) already and it should be used here too as it’s accessible for keyboard and screen reader users

**Comment by iamanishroy** [comment]
I am working on it

**Comment by shamsmosowi** [comment]
Hi @iamanishroy , search is need specially when tables get big, 
why is it necessary to remove search or have separate menu?
you can elaborate on the blocker you're facing

**Comment by shamsmosowi** [comment]
oh, i see, i think the solution would that the ordering feature is disabled if a filter is applied

**Comment by harinij** [comment]
Merged to develop
