### ISSUE TITLE
Clicking on subtable field results in redirection of the URL, remove it to fix nav issue

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#634]
**Describe the bug**
Currently, the links to subtable end with the URL "?parentLabel=" which seems to redirect to a URL ending with "?rowRef=". This causes issue when trying to navigate back with the back button, as instead of going back to the main table it goes to the original URL.

**To Reproduce**
1. Go to a table with a subtable (example:[All fields demo table]( https://demo.rowy.io/table/allFieldTypes))
2. Click on a subtable value (notice how the URL redirects from "?parentLabel=" to "?rowRef=" at the end)
3. Click the back button in your browser
4. This will not take you to the main table as expected, you have to click the back button again to do so.

**Expected behavior**
Is there a reason for this redirection in URL to exist? if not it would be best to remove it.

**Comment by notsidney** [comment]
`rowRef` is used to make the URL link to the specific row that’s selected. `parentLabel` is used to display a label for the parent document of the sub-collection you’re viewing.

It looks like the code written for both overwrites the entire URL query string instead of modifying just one part of the query string. This should be migrated to Jotai’s `atomWithHash`
