### ISSUE TITLE
Rowy.io stuck on login via GitHub

### ISSUE THREAD

**Issue by yaozhang-this** [rowyio/rowy#837]
**Describe the bug**
Rowy.io stuck on login via GitHub

After setting up the firebase connection via the recommended flow on the website, I can not log in to my account via my registered GitHub account and the frontend displays a "Continue with" string and does not lead me to anywhere.

The url of which I got stuck on is "https://rowy.app/auth?redirect=%2F"

Tried this in Firefox and same behavior is displayed.

**To Reproduce**
1. Go through the registration flow in rowy, and log in
2. Behavior emerged.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Safari]
 - Version [15.6.1]

**Comment by eldadcaspi** [comment]
Here too, but with Google's login. 
I think that the new Workspaces concept does not merge well with existing rowy's permissions on gcp. 

<img width="1728" alt="Screen Shot 2022-09-23 at 11 23 46" src="https://user-images.githubusercontent.com/4774962/191920301-611d0beb-dc4f-4b00-b68a-f1a6a63ac390.png">

**Comment by notsidney** [comment]
Hi, have you previously signed in with Google or Microsoft with the same email as your GitHub account?

We currently have an issue with the UI library we’re using for auth, firebaseui, not handling this use case anymore. Relevant issues:
- https://github.com/firebase/firebaseui-web/issues/921
- https://github.com/firebase/firebaseui-web/issues/928
- https://github.com/firebase/firebase-js-sdk/issues/4926

Unfortunately there hasn’t been an update since February so we may have to build our own auth UI.

**Comment by bofeiw** [comment]
We have fixed this issue on rowy.app.

**Comment by Chuiantw1212** [comment]
@bofeiw 
Hi, would you mind sharing your solutions?
I have cloned the rowy source code and did a little research, could not figure out how you guy resolve it.
